### PR TITLE
Add rte config attribute

### PR DESCRIPTION
**Pull request by fkroockmann**
Now rte-Config data is available for editable content

### CODE REVIEW

**Comment by crouillon** [comment]
:+1:

**Comment by eric-chau** [comment]
In the end we have alot of `data` in the HTML like the previous version ^^ :+1:

**Comment by fkroockmann** [comment]
That for avoid a rest call :/

**Comment by eric-chau** [comment]
I know ^^ but it's the opposite side of what we wanted at the beginning.

**Comment by fkroockmann** [comment]
Yes but that just on BO side.

**Pull request merged**
