### PR TITLE
backbee/backbee-standard#101 : Prepare 1.0.0

### PR DESCRIPTION
**Pull request by nicolas-bastien**
backbee/backbee-standard#101 : Prepare 1.0.0 release

### CODE REVIEW

**Comment by nicolas-bastien** [comment]
Hi @mickaelandrieu,

I tried to install it but it fails because there isn't any backbee/client-js ?
Maybe something you haven't released yet ?

**Comment by mickaelandrieu** [comment]
you can't require an hypothetic 1.0.*@dev of ``backbee/client-js`` this way.

We need to create a package for our javascript client (/c @ndufreche ). When you use repositories to access repositories which don't have any composer.json file, you must have a "dev-" branch.

**Comment by nicolas-bastien** [comment]
@mickaelandrieu you're right I didn't pay attention to this.

I'm not sure this way is the best.

I think first we should install client-js with composer to so we can have versionning and your moveClient task will work just fine.

Then we can imagine using bower couple with gruntJs to get it directly in the backbee-standard but I don't use bower so much and I think the best for 1.0.0 is to get something stable.

**Comment by nicolas-bastien** [comment]
Refactor to fit https://github.com/backbee/BbCoreJs/pull/316 changes

@mickaelandrieu you need to add backbee/bb-core-js to packagist

**Comment by nicolas-bastien** [comment]
Depends on https://github.com/backbee/ToolbarBundle/pull/38

**Comment by nicolas-bastien** [comment]
Wainting backbee/bb-core-js to be register on packagist

As https://github.com/backbee/BbCoreJs/pull/316 has been merged do you need something else ?

**Comment by mickaelandrieu** [comment]
@nicolas-bastien done (https://packagist.org/packages/backbee/bb-core-js) but we now new an update of ``ToolbarBundle`` and ``backbee-standard`` and ``ScriptHandler`` (update the path of the dependency)

**Comment by nicolas-bastien** [comment]
ok so seams ok to merge this ?

backbee-standard PR is ready too : https://github.com/backbee/backbee-standard/pull/102

ComposerHandler : https://github.com/backbee/ComposerHandler/pull/4

**Pull request merged**
