### PR TITLE
Add root uid in data of toolbar

### PR DESCRIPTION
**Pull request by fkroockmann**
Add root uid in data of toolbar

### CODE REVIEW

**Comment by eric-chau** [comment]
Can you just explain why you need this so we can be sure that this is useful? ^^ thank you

**Comment by fkroockmann** [comment]
In the javascript project, we need to get the root uid several times. this avoir to call it in REST

**Comment by eric-chau** [comment]
ok nice :+1:

**Comment by fkroockmann** [comment]
thanks for review @eric-chau

**Pull request merged**
